litemall:
  goods-distribution: true
  leshua:
    url: https://paygate.leshuazf.com/
    merchant_id: 4014116132
    key: EE085A0ABA9D22493B7971B2E1AEB4DF
    notify-key: A79CE8B83C9BAA666353B7CA80F4616B
    pay-notify-url: http://20b75fd6.ngrok.io/wx/order/pay-notify-leshua
    refund-notify-url: http://20b75fd6.ngrok.io/admin/order/refund-notify-leshua

  # 开发者应该设置成自己的wx相关信息
  wx:
#    app-id: wxc2c84d6c53366329
#    app-secret: 4c8e07a7311c70d781abba25dc458344
    app-id: wx080d8c9a162dc2b1
    app-secret: 0418ccad717ef9aa6298dc3d9344e04c
    mch-id: 1534210531
    mch-key: dme0kMJgZ1KJ4aRC59cgXQZvdv0YEFAp
    notify-url: http://www.example.com/wx/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx
    aes-key: dme0kMJgZ1KJ4aRC59cgXQZvdv0YEFAp

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: false
      host: smtp.exmail.qq.com
      username: ex@ex.com.cn
      password: XXXXXXXXXXXXX
      sendfrom: ex@ex.com.cn
      sendto: ex@qq.com
      port: 465
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      # 如果是腾讯云短信，则设置active的值tencent
      # 如果是阿里云短信，则设置active的值aliyun
      active: tencent
      sign: litemall
      template:
      - name: paySucceed
        templateId: 156349
      - name: captcha
        templateId: 156433
      - name: ship
        templateId: 158002
      - name: refund
        templateId: 159447
      tencent:
        appid: 111111111
        appkey: xxxxxxxxxxxxxx
      aliyun:
        regionId: xxx
        accessKeyId: xxx
        accessKeySecret: xxx

  # 快鸟物流查询配置
  express:
    enable: false
    appId: "XXXXXXXXX"
    appKey: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    vendors:
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: litemall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
      secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
      region: ap-shanghai
      bucketName: vytech-1300096589
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall